name: the_play
description: "더플레이"
homepage: https://theplay.com
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

#version
version: 1.0.0+1

#environment
environment:
  sdk: '>=3.4.3 <4.0.0'

#dependencies
dependencies:
  flutter:
    sdk: flutter

  # custom dependencies
  animations: ^2.0.7
  collection: ^1.17.0
  connectivity_plus: ^6.0.1
  device_info_plus: ^9.1.0
  dio: ^5.0.0
  dio_cache_interceptor: ^3.4.0
  dynamic_color: ^1.6.3
  dynamic_themes: ^1.1.0
  expandable: ^5.0.1

  flutter_cache_manager: ^3.3.0
  flutter_file_dialog: ^3.0.2
  flutter_local_notifications: ^16.1.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.14
  fluttertoast: ^8.2.4
  font_awesome_flutter: ^10.4.0
  google_fonts: ^6.2.1
  injectable: ^2.1.1
  intl: ^0.19.0
  json_annotation: ^4.8.1
  language_code: ^0.5.1

  package_info_plus: ^6.0.0
  path_provider: ^2.0.14
  permission_handler: ^11.0.1

  share_plus: ^7.2.1
  shared_preferences: ^2.1.0
  skeletons: ^0.0.3
  slang: ^3.25.0
  slang_flutter: ^3.25.0
  stacked: ^3.2.0
  stacked_generator: ^1.1.0
  stacked_services: ^1.0.0
  synchronized: ^3.1.0
  timeago: ^3.3.0
  timezone: ^0.9.0
  url_launcher: ^6.1.10
  wakelock_plus: ^1.1.3

  cached_network_image: ^3.3.1
  http: ^1.2.1

  provider: ^6.0.1

  #####################
  ### login
  #####################
#  google_sign_in: ^5.4.1
#  flutter_facebook_auth: ^4.0.4
#  sign_in_with_apple: ^3.0.0
  kakao_flutter_sdk: ^1.9.2
#  naver_login: ^1.2.2

  #####################
  ### video
  #####################
  video_player: ^2.1.12

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
